
CREATE DATABASE [fleetQueries]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fleetADC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\fleetADC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fleetADC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\fleetADC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [fleetQueries] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fleetQueries].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [fleetQueries] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [fleetQueries] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [fleetQueries] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [fleetQueries] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [fleetQueries] SET ARITHABORT OFF 
GO
ALTER DATABASE [fleetQueries] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [fleetQueries] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [fleetQueries] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [fleetQueries] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [fleetQueries] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [fleetQueries] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [fleetQueries] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [fleetQueries] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [fleetQueries] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [fleetQueries] SET  DISABLE_BROKER 
GO
ALTER DATABASE [fleetQueries] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [fleetQueries] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [fleetQueries] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [fleetQueries] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [fleetQueries] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [fleetQueries] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [fleetQueries] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [fleetQueries] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [fleetQueries] SET  MULTI_USER 
GO
ALTER DATABASE [fleetQueries] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [fleetQueries] SET DB_CHAINING OFF 
GO
ALTER DATABASE [fleetQueries] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [fleetQueries] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [fleetQueries] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [fleetQueries] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [fleetQueries] SET QUERY_STORE = OFF
GO
USE [fleetQueries]
GO
/****** Object:  Table [dbo].[CORTICON_ADC_READ]    Script Date: 9/13/2024 1:43:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORTICON_ADC_READ](
	[ID] [bigint] NOT NULL,
	[NAME] [varchar](100) NULL,
	[ADD_TO_PAYLOAD] [varchar](20) NULL,
 CONSTRAINT [CORTICON_ADC_READ_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CORTICON_ADC_READ_DEFS]    Script Date: 9/13/2024 1:43:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORTICON_ADC_READ_DEFS](
	[ID] [bigint] NOT NULL,
	[READ_ID] [bigint] NULL,
	[SEQUENCE] [bigint] NULL,
	[SQL] [varchar](500) NULL,
	[PRIMARY_ENTITY] [varchar](50) NULL,
	[PARENT_ENTITY] [varchar](50) NULL,
	[PARENT_ROLENAME] [varchar](50) NULL,
	[ENABLE] [varchar](20) NULL,
 CONSTRAINT [CORTICON_ADC_READ_DEFS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CORTICON_ADC_WRITE]    Script Date: 9/13/2024 1:43:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORTICON_ADC_WRITE](
	[ID] [bigint] NOT NULL,
	[NAME] [varchar](100) NULL,
 CONSTRAINT [CORTICON_ADC_WRITE_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CORTICON_ADC_WRITE_DEFS]    Script Date: 9/13/2024 1:43:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORTICON_ADC_WRITE_DEFS](
	[ID] [bigint] NOT NULL,
	[WRITE_ID] [bigint] NULL,
	[SEQUENCE] [bigint] NULL,
	[SQL] [varchar](500) NULL,
	[PRIMARY_ENTITY] [varchar](50) NULL,
	[ENABLE] [varchar](20) NULL,
 CONSTRAINT [CORTICON_ADC_WRITE_DEFS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CORTICON_ADC_READ] ([ID], [NAME], [ADD_TO_PAYLOAD]) VALUES (1, N'driverStatus', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ] ([ID], [NAME], [ADD_TO_PAYLOAD]) VALUES (3, N'maintenanceForVehicle', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ] ([ID], [NAME], [ADD_TO_PAYLOAD]) VALUES (4, N'tripWaypoints', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ] ([ID], [NAME], [ADD_TO_PAYLOAD]) VALUES (5, N'udf', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (1, 1, 1, N'SELECT * FROM Driver', N'Driver', NULL, NULL, N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (2, 1, 2, N'SELECT * FROM DriverStatusChange WHERE driverId IN ({Driver.driverID})', N'DriverStatusChange', N'Driver', N'driverStatusChange ', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (5, 3, 1, N'SELECT * FROM Vehicle', N'Vehicle', NULL, NULL, N'
true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (6, 3, 2, N'SELECT * FROM MaintenanceRecord WHERE VehicleID IN ({Vehicle.tagNo})', N'MaintenanceRecord ', N'Vehicle', N'maintenanceRecord ', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (7, 4, 2, N'SELECT * FROM Origin WHERE tripID IN  ({Trip.tripID})', N'TripOrigin', N'Trip', N'tripOrigin', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (8, 4, 3, N'SELECT * FROM Destination WHERE tripID IN  ({Trip.tripID})', N'TripDestination', N'Trip', N'tripDestination', N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (9, 4, 1, N'SELECT * FROM Trip WHERE tripID IN ({Trip.tripID})', N'Trip', NULL, NULL, N'true')
GO
INSERT [dbo].[CORTICON_ADC_READ_DEFS] ([ID], [READ_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [PARENT_ENTITY], [PARENT_ROLENAME], [ENABLE]) VALUES (10, 5, 1, N'SELECT * FROM TripDetailsView WHERE tripID IN ({Trip.tripID})', N'Trip', NULL, NULL, N'true')
GO
INSERT [dbo].[CORTICON_ADC_WRITE] ([ID], [NAME]) VALUES (1, N'UpdateStart')
GO
INSERT [dbo].[CORTICON_ADC_WRITE_DEFS] ([ID], [WRITE_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [ENABLE]) VALUES (1, 1, 1, N'UPDATE DriverStatusChange SET statusStart=({DriverStatusChange.statusStart}) WHERE driverId=({DriverStatusChange.driverId})', N'DriverStatusChange ', N'true')
GO
INSERT [dbo].[CORTICON_ADC_WRITE_DEFS] ([ID], [WRITE_ID], [SEQUENCE], [SQL], [PRIMARY_ENTITY], [ENABLE]) VALUES (2, 1, 2, N'UPDATE DriverStatusChange SET statusEnd=({DriverStatusChange.statusEnd}) WHERE driverId=({DriverStatusChange.driverId})', N'DriverStatusChange ', N'true')
GO
ALTER TABLE [dbo].[CORTICON_ADC_READ_DEFS]  WITH CHECK ADD FOREIGN KEY([READ_ID])
REFERENCES [dbo].[CORTICON_ADC_READ] ([ID])
GO
ALTER TABLE [dbo].[CORTICON_ADC_WRITE_DEFS]  WITH CHECK ADD FOREIGN KEY([WRITE_ID])
REFERENCES [dbo].[CORTICON_ADC_WRITE] ([ID])
GO
USE [master]
GO
ALTER DATABASE [fleetQueries] SET  READ_WRITE 
GO
