<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="7" minorServiceNumber="3" buildNumber="8021" updateStamp="_hrYKkYctEe-R86uBy0z3mg" externalChecksum="2722078124:507989954" studioType="Java" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Candy">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Candy"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="discard"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasNuts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="hasNuts"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inProperPackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="inProperPackage"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFruit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isFruit"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="replace"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//Child" eOpposite="#//Child/candy">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="child"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Child"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="candyOwed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="candyOwed"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daysAtThreePieces" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="daysAtThreePieces"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="piecesForThirtyDays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="piecesForThirtyDays"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="candy" upperBound="-1" eType="#//Candy" eOpposite="#//Candy/child">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="candy"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="candyCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="candyCount"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
